coverage:
  status:
    project:
      default: off
      production:
        target: auto
        flags:
          - production
fixes:
  - "src/monitor/::"
flags:
  production:
    paths:
      - "*/src/**/*"
  test:
    paths:
      - "*/test/*"
