pub_rate: 1.0
base_path: ''
analyzers:
  temperatures:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Temperatures
    contains: 'Temperature'
    remove_prefix: 'march_rqt_robot_monitor_node: '
  inputs:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Inputs
    contains: 'input_device'
    remove_prefix: 'march_rqt_robot_monitor_node: '
  control:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Control
    contains: 'Control'
    remove_prefix: 'march_rqt_robot_monitor_node: '
  imotioncubes:
    type: diagnostic_aggregator/GenericAnalyzer
    path: iMotioncubes
    contains: 'IMC'
    remove_prefix: 'march_rqt_robot_monitor_node: IMC '
